// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzzfmfszztpithguiuzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6emZtZnN6enRwaXRoZ3VpdXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTIxNDcsImV4cCI6MjA2ODU4ODE0N30._iJ-i53-uu_EqRGOc-OEpLcLaxu3sqx47WqxRMYl9Mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});